# Generated by Django 2.2 on 2021-07-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_auto_20210622_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль'},
        ),
    ]
