# Generated by Django 2.2 on 2021-06-17 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя блога')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateField(auto_now_add=True, verbose_name='Дата последнего поста')),
                ('author_info', models.CharField(max_length=200, verbose_name='Информация о себе')),
                ('nickname', models.CharField(blank=True, max_length=80, verbose_name='Прозвище')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='app_blogs.Blog', verbose_name='Блог')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['date_updated'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='image_posts', verbose_name='Изображения')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_image', to='app_blogs.Post')),
            ],
        ),
    ]
